# Generated by Django 4.1.4 on 2022-12-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_color_alter_product_category_product_color_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_choice',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
